@startuml

class Client {
}

interface Subject {
    action()
}
class Proxy {
    action()
}
class RealSubject {
    action()
}

Client ..> Subject

Subject <|-- Proxy
Subject <|-- RealSubject
Proxy -> RealSubject

@enduml
