@startuml

class Component {
    operation()
}
class Leaf {
    operation()
}
class Composite {
    operation()
    add()
}
Component <|-- Leaf
Component <|-- Composite
Composite o--> Component

@enduml
