@startuml

class Context {
    request()
}

interface State {
    handle()
}
Context o--> State
State ..> Context

class ConcreteStateA {
}
State <|-- ConcreteStateA

class ConcreteStateB {
}
State <|-- ConcreteStateB

@enduml
