@startuml

class Director {
    Implementor
    build()
}

interface Builder {
    operation_impl()
}
Director o-- Builder

class ConcreteBuilder {
    operation_impl()
}
Builder <|-- ConcreteBuilder

class Product {
}
ConcreteBuilder ..> Product

@enduml
