@startuml

interface Flyweight {
    operation()
}
class ConcreteFlyweight {
    operation()
}
class Client {
}
class FlyweightFactory {
    get_flyweight()
}

FlyweightFactory o--> Flyweight
ConcreteFlyweight --|> Flyweight
Client --> FlyweightFactory
Client --> ConcreteFlyweight

@enduml
