@startuml

class Client {
}

interface Handler {
    handle_request()
}
Handler --> Handler
Client --> Handler

interface ConcreteHandler1 {
    handle_request()
}
interface ConcreteHandler2 {
    handle_request()
}

Handler <|-- ConcreteHandler1
Handler <|-- ConcreteHandler2

@enduml
