@startuml

interface Abstraction {
    Implementor
}

class RefinedAbstraction {
    refinedFunction()
}
Abstraction <|-- RefinedAbstraction

interface Implementor {
    OperationImpl()
}
Abstraction o-- Implementor

class ConcreteImplementationA {
    OperationImpl()
}
class ConcreteImplementationB {
    OperationImpl()
}
Implementor <|-- ConcreteImplementationA
Implementor <|-- ConcreteImplementationB

@enduml